FROM mercury/python-subrepo

ENV INSTALL_DIRECTORY=/tmp

ADD test_requirements.txt ${INSTALL_DIRECTORY}
ADD requirements.txt ${INSTALL_DIRECTORY}

RUN pip install coverage \
    && pip install -r ${INSTALL_DIRECTORY}/test_requirements.txt \
    && pip install -r ${INSTALL_DIRECTORY}/requirements.txt

RUN git config --global user.email "example@example.com" \
    && git config --global user.name example

RUN rm ${INSTALL_DIRECTORY}/*requirements.txt
